Update BashScript
Am modificat BashScriptul

diff --git a/BashScript b/BashScript
--- a/BashScript
+++ b/BashScript
@@ -1,4 +1,9 @@
 
+
+#!/bin/bash
+
+path=$1
+
 function Download ()
 {
         pushd /tmp/
@@ -12,10 +17,14 @@ function Download ()
 
 function InstallGeekbenchDependencies ()
 {
-        [[ $(uname -p) = "x86_64" ]] && sudo apt-get install -y libc6:i386 libstdc++6:i386
+        [[ $(uname -p) = "x86_64" ]] 
         if [ $? -eq 0 ]; then
-        echo "Error: unable to install dependencies"
-        else echo "Installing Geekbench Dependencies completed."
+	sudo apt-get install -y libc6:i386 libstdc++6:i386
+	if [ $? -eq 0 ]; then
+	echo "Installing Geekbench Dependencies completed."
+	else "Failed installing Geekbench Dependencies."
+	fi
+	else "Geekbench Dependencies not needed for 32 bits."
         fi
 }
 
@@ -23,14 +32,34 @@ function InstallGeekbench ()
 {
         pushd /tmp/
         tar xvf Geekbench-3.3.2-Linux.tar.gz
+	if [ $? -eq 0 ]; then
+	echo "Successful unzipping process."
+	else echo "Failed unzipping archive."
+	fi
         popd
 }
 
 function RunExport ()
 {
-        pushd /tmp/dist/Geekbench-3.3.2-Linux
-        [[ $(uname -p) = "x86_64" ]] && ./geekbench_x86_64 >> log.txt
-        [[ $(uname -p) = "x86_32" ]] && ./geekbench_x86_32 >> log.txt
+       pushd /tmp/dist/Geekbench-3.3.2-Linux
+        [[ $(uname -p) = "x86_64" ]]
+        if [ $? -eq 0 ]; then
+        ./geekbench_x86_64 >> log.txt
+        mv log.txt /home/ingrid/new_dir
+        if [ $? -eq 0 ]; then
+        echo "Successful run and export."
+        else echo "Failed running and exporting."
+        fi
+        fi
+        [[ $(uname -p) = "x86_32" ]]
+        if [ $? -eq 0 ]; then
+        ./geekbench_x86_32 >> log.txt
+        mv log.txt /home/ingrid/new_dir
+        if [ $? -eq 0 ]; then
+        echo "Successful run and export."
+        else echo "Failed run and export."
+        fi
+        fi
         popd
 }
 
@@ -40,5 +69,6 @@ Download
 InstallGeekbenchDependencies
 InstallGeekbench
 RunExport
+
 
 
